import { type Language } from '../components/LanguageSelector';
import { type KnowledgeModule } from '../components/ModuleCard';

export const knowledgeModules: KnowledgeModule[] = [
  {
    id: 'gst',
    category: 'gst',
    icon: '/assets/generated/icon-gst.dim_128x128.png',
    title: {
      english: 'GST Filing',
      hindi: 'जीएसटी फाइलिंग',
      marathi: 'जीएसटी फाइलिंग',
    },
    description: {
      english: 'Learn how to register, collect, and file GST returns for your shop.',
      hindi: 'अपनी दुकान के लिए जीएसटी रजिस्ट्रेशन, संग्रह और रिटर्न फाइलिंग सीखें।',
      marathi: 'तुमच्या दुकानासाठी जीएसटी नोंदणी, संकलन आणि परतावा फाइलिंग शिका.',
    },
    tips: {
      english: [
        'Register on gst.gov.in if your annual turnover exceeds ₹20 lakhs (₹10 lakhs for special states).',
        'Add GST to every customer bill — 5%, 12%, 18%, or 28% depending on your product.',
        'File GSTR-1 by the 11th of every month to report your sales.',
        'File GSTR-3B by the 20th of every month and pay the tax due.',
        'Keep all purchase and sales invoices for at least 6 years.',
        'Use Vyapar or Tally app to automatically calculate GST on bills.',
        'If you miss a filing deadline, a late fee of ₹50/day applies.',
        'Input Tax Credit (ITC) lets you deduct GST paid on purchases from GST collected on sales.',
      ],
      hindi: [
        'gst.gov.in पर रजिस्टर करें अगर सालाना टर्नओवर ₹20 लाख से ज्यादा है।',
        'हर ग्राहक के बिल में जीएसटी जोड़ें — 5%, 12%, 18%, या 28% प्रोडक्ट के अनुसार।',
        'हर महीने 11 तारीख तक GSTR-1 भरें (बिक्री की जानकारी)।',
        'हर महीने 20 तारीख तक GSTR-3B भरें और टैक्स जमा करें।',
        'सभी खरीद और बिक्री के बिल कम से कम 6 साल तक रखें।',
        'Vyapar या Tally ऐप से बिल पर जीएसटी अपने आप कैलकुलेट होगा।',
        'देर से फाइल करने पर ₹50/दिन का जुर्माना लगता है।',
        'इनपुट टैक्स क्रेडिट (ITC) से खरीद पर चुकाया जीएसटी वापस मिलता है।',
      ],
      marathi: [
        'gst.gov.in वर नोंदणी करा जर वार्षिक उलाढाल ₹20 लाखांपेक्षा जास्त असेल.',
        'प्रत्येक ग्राहकाच्या बिलात जीएसटी जोडा — उत्पादनानुसार 5%, 12%, 18%, किंवा 28%.',
        'दर महिन्याच्या 11 तारखेपर्यंत GSTR-1 भरा (विक्रीची माहिती).',
        'दर महिन्याच्या 20 तारखेपर्यंत GSTR-3B भरा आणि कर भरा.',
        'सर्व खरेदी आणि विक्रीची बिले किमान 6 वर्षे ठेवा.',
        'Vyapar किंवा Tally अॅपने बिलावर जीएसटी आपोआप मोजला जाईल.',
        'उशिरा फाइल केल्यास ₹50/दिवस दंड लागतो.',
        'इनपुट टॅक्स क्रेडिट (ITC) ने खरेदीवर भरलेला जीएसटी परत मिळतो.',
      ],
    },
  },
  {
    id: 'payments',
    category: 'payments',
    icon: '/assets/generated/icon-payments.dim_128x128.png',
    title: {
      english: 'Digital Payments',
      hindi: 'डिजिटल पेमेंट',
      marathi: 'डिजिटल पेमेंट',
    },
    description: {
      english: 'Accept UPI, QR code, and card payments easily at your shop.',
      hindi: 'अपनी दुकान पर UPI, QR कोड और कार्ड पेमेंट आसानी से स्वीकार करें।',
      marathi: 'तुमच्या दुकानात UPI, QR कोड आणि कार्ड पेमेंट सहजपणे स्वीकारा.',
    },
    tips: {
      english: [
        'Download PhonePe, Google Pay, or Paytm and link your bank account to get started.',
        'Generate a QR code from your UPI app and print it — customers can scan and pay instantly.',
        'UPI payments are free for both you and your customers.',
        'Money reaches your bank account within seconds to minutes.',
        'Keep your UPI PIN secret — never share it with anyone.',
        'Check your bank statement weekly to verify all payments received.',
        'For large amounts, ask customers to show payment confirmation before giving goods.',
        'Apply for a POS machine from your bank for card payments (small fee per transaction).',
      ],
      hindi: [
        'PhonePe, Google Pay, या Paytm डाउनलोड करें और बैंक अकाउंट लिंक करें।',
        'UPI ऐप से QR कोड बनाएं और प्रिंट करें — ग्राहक स्कैन करके तुरंत पेमेंट करेंगे।',
        'UPI पेमेंट आपके और ग्राहक दोनों के लिए मुफ्त है।',
        'पैसे कुछ सेकंड से मिनटों में बैंक अकाउंट में आ जाते हैं।',
        'UPI PIN गुप्त रखें — किसी को भी न बताएं।',
        'हर हफ्ते बैंक स्टेटमेंट चेक करें।',
        'बड़ी रकम के लिए सामान देने से पहले पेमेंट कन्फर्मेशन देखें।',
        'कार्ड पेमेंट के लिए बैंक से POS मशीन के लिए आवेदन करें।',
      ],
      marathi: [
        'PhonePe, Google Pay, किंवा Paytm डाउनलोड करा आणि बँक खाते लिंक करा.',
        'UPI अॅपमधून QR कोड तयार करा आणि प्रिंट करा — ग्राहक स्कॅन करून लगेच पेमेंट करतात.',
        'UPI पेमेंट तुमच्यासाठी आणि ग्राहकांसाठी दोन्हींसाठी मोफत आहे.',
        'पैसे काही सेकंद ते मिनिटांत बँक खात्यात येतात.',
        'UPI PIN गुप्त ठेवा — कोणालाही सांगू नका.',
        'दर आठवड्याला बँक स्टेटमेंट तपासा.',
        'मोठ्या रकमेसाठी माल देण्यापूर्वी पेमेंट कन्फर्मेशन पहा.',
        'कार्ड पेमेंटसाठी बँकेकडून POS मशीनसाठी अर्ज करा.',
      ],
    },
  },
  {
    id: 'security',
    category: 'security',
    icon: '/assets/generated/icon-security.dim_128x128.png',
    title: {
      english: 'IT Security',
      hindi: 'IT सुरक्षा',
      marathi: 'IT सुरक्षा',
    },
    description: {
      english: 'Protect your phone, data, and money from fraud and cyber threats.',
      hindi: 'धोखाधड़ी और साइबर खतरों से अपना फोन, डेटा और पैसा सुरक्षित रखें।',
      marathi: 'फसवणूक आणि सायबर धोक्यांपासून तुमचा फोन, डेटा आणि पैसे सुरक्षित ठेवा.',
    },
    tips: {
      english: [
        'Set a strong 6-digit PIN or fingerprint lock on your phone.',
        'Enable 2-Step Verification on WhatsApp: Settings → Account → Two-step verification.',
        'Never share OTP, PIN, or password with anyone — not even bank employees.',
        'Only download apps from Google Play Store or Apple App Store.',
        'Update your phone software regularly to fix security holes.',
        'Be suspicious of calls claiming to be from banks, police, or government.',
        'Do not click on unknown links in SMS or WhatsApp messages.',
        'Use different passwords for different apps and accounts.',
      ],
      hindi: [
        'फोन पर मजबूत 6-अंकीय PIN या फिंगरप्रिंट लॉक लगाएं।',
        'WhatsApp पर 2-स्टेप वेरिफिकेशन चालू करें: Settings → Account → Two-step verification।',
        'OTP, PIN, या पासवर्ड किसी को भी न बताएं — बैंक कर्मचारी को भी नहीं।',
        'सिर्फ Google Play Store या Apple App Store से ऐप डाउनलोड करें।',
        'फोन का सॉफ्टवेयर नियमित रूप से अपडेट करें।',
        'बैंक, पुलिस, या सरकार बनकर आने वाले कॉल से सावधान रहें।',
        'SMS या WhatsApp में अनजान लिंक पर क्लिक न करें।',
        'अलग-अलग ऐप और अकाउंट के लिए अलग पासवर्ड रखें।',
      ],
      marathi: [
        'फोनवर मजबूत 6-अंकी PIN किंवा फिंगरप्रिंट लॉक लावा.',
        'WhatsApp वर 2-स्टेप व्हेरिफिकेशन चालू करा: Settings → Account → Two-step verification.',
        'OTP, PIN, किंवा पासवर्ड कोणालाही सांगू नका — बँक कर्मचाऱ्यालाही नाही.',
        'फक्त Google Play Store किंवा Apple App Store वरून अॅप डाउनलोड करा.',
        'फोनचे सॉफ्टवेअर नियमितपणे अपडेट करा.',
        'बँक, पोलीस, किंवा सरकार म्हणून येणाऱ्या कॉलपासून सावध राहा.',
        'SMS किंवा WhatsApp मधील अनोळखी लिंकवर क्लिक करू नका.',
        'वेगवेगळ्या अॅप आणि खात्यांसाठी वेगळे पासवर्ड वापरा.',
      ],
    },
  },
  {
    id: 'marketing',
    category: 'marketing',
    icon: '/assets/generated/icon-marketing.dim_128x128.png',
    title: {
      english: 'Online Marketing',
      hindi: 'ऑनलाइन मार्केटिंग',
      marathi: 'ऑनलाइन मार्केटिंग',
    },
    description: {
      english: 'Attract more customers using WhatsApp, Google, and social media.',
      hindi: 'WhatsApp, Google और सोशल मीडिया से ज्यादा ग्राहक आकर्षित करें।',
      marathi: 'WhatsApp, Google आणि सोशल मीडियाद्वारे अधिक ग्राहक आकर्षित करा.',
    },
    tips: {
      english: [
        'Create a WhatsApp Business account — add your shop name, address, hours, and catalog.',
        'Register on Google My Business (free) so customers can find you in Google Maps.',
        'Post photos of your products on Facebook and Instagram with local hashtags.',
        'Send festival offers and discounts to your WhatsApp customer groups.',
        'Ask satisfied customers to leave a Google review — it builds trust.',
        'Use WhatsApp Status to share daily offers (visible to all your contacts).',
        'Create a simple product catalog on WhatsApp Business for easy browsing.',
        'Reply to customer messages within 1 hour to build a good reputation.',
      ],
      hindi: [
        'WhatsApp Business अकाउंट बनाएं — दुकान का नाम, पता, समय और कैटलॉग जोड़ें।',
        'Google My Business पर रजिस्टर करें (मुफ्त) ताकि ग्राहक Google Maps पर आपको ढूंढ सकें।',
        'Facebook और Instagram पर लोकल हैशटैग के साथ प्रोडक्ट फोटो पोस्ट करें।',
        'WhatsApp ग्राहक ग्रुप में त्योहारी ऑफर और छूट भेजें।',
        'संतुष्ट ग्राहकों से Google रिव्यू देने को कहें — इससे विश्वास बनता है।',
        'WhatsApp Status पर रोज के ऑफर शेयर करें।',
        'WhatsApp Business पर सरल प्रोडक्ट कैटलॉग बनाएं।',
        'ग्राहकों के मैसेज का 1 घंटे के अंदर जवाब दें।',
      ],
      marathi: [
        'WhatsApp Business खाते तयार करा — दुकानाचे नाव, पत्ता, वेळ आणि कॅटलॉग जोडा.',
        'Google My Business वर नोंदणी करा (मोफत) जेणेकरून ग्राहक Google Maps वर तुम्हाला शोधू शकतात.',
        'Facebook आणि Instagram वर स्थानिक हॅशटॅगसह उत्पादन फोटो पोस्ट करा.',
        'WhatsApp ग्राहक गटात सणासुदीचे ऑफर आणि सवलती पाठवा.',
        'समाधानी ग्राहकांना Google रिव्ह्यू देण्यास सांगा — यामुळे विश्वास निर्माण होतो.',
        'WhatsApp Status वर रोजचे ऑफर शेअर करा.',
        'WhatsApp Business वर साधी उत्पादन कॅटलॉग तयार करा.',
        'ग्राहकांच्या संदेशांना 1 तासाच्या आत उत्तर द्या.',
      ],
    },
  },
  {
    id: 'accounting',
    category: 'accounting',
    icon: '/assets/generated/icon-accounting.dim_128x128.png',
    title: {
      english: 'Simple Accounting',
      hindi: 'सरल हिसाब-किताब',
      marathi: 'सोपे हिशोब',
    },
    description: {
      english: 'Track your daily sales, expenses, and profits with simple tools.',
      hindi: 'सरल टूल्स से रोज की बिक्री, खर्च और मुनाफा ट्रैक करें।',
      marathi: 'सोप्या साधनांनी रोजची विक्री, खर्च आणि नफा ट्रॅक करा.',
    },
    tips: {
      english: [
        'Record every sale in a notebook or app — even ₹10 sales matter.',
        'Use Khatabook app to track credit given to customers (free, Hindi/Marathi support).',
        'Use Vyapar app for billing, inventory, and GST — free for basic features.',
        'Calculate daily profit: Total Sales − Total Expenses = Profit.',
        'Set aside 10-15% of profit for taxes and emergencies.',
        'Review your top-selling products every month and stock more of them.',
        'Keep personal and business money separate — open a separate bank account.',
        'Take a photo of every receipt and store it in Google Drive for easy access.',
      ],
      hindi: [
        'हर बिक्री नोटबुक या ऐप में दर्ज करें — ₹10 की बिक्री भी मायने रखती है।',
        'Khatabook ऐप से ग्राहकों को दिया उधार ट्रैक करें (मुफ्त, हिंदी/मराठी सपोर्ट)।',
        'बिलिंग, इन्वेंटरी और जीएसटी के लिए Vyapar ऐप इस्तेमाल करें।',
        'रोज का मुनाफा निकालें: कुल बिक्री − कुल खर्च = मुनाफा।',
        'मुनाफे का 10-15% टैक्स और आपात स्थिति के लिए अलग रखें।',
        'हर महीने सबसे ज्यादा बिकने वाले प्रोडक्ट की समीक्षा करें।',
        'व्यक्तिगत और बिजनेस पैसे अलग रखें — अलग बैंक अकाउंट खोलें।',
        'हर रसीद की फोटो लें और Google Drive में सेव करें।',
      ],
      marathi: [
        'प्रत्येक विक्री वहीत किंवा अॅपमध्ये नोंदवा — ₹10 ची विक्री देखील महत्त्वाची आहे.',
        'Khatabook अॅपने ग्राहकांना दिलेले उधार ट्रॅक करा (मोफत, हिंदी/मराठी सपोर्ट).',
        'बिलिंग, इन्व्हेंटरी आणि जीएसटीसाठी Vyapar अॅप वापरा.',
        'रोजचा नफा काढा: एकूण विक्री − एकूण खर्च = नफा.',
        'नफ्याचे 10-15% कर आणि आणीबाणीसाठी बाजूला ठेवा.',
        'दर महिन्याला सर्वाधिक विकल्या जाणाऱ्या उत्पादनांचा आढावा घ्या.',
        'वैयक्तिक आणि व्यवसायाचे पैसे वेगळे ठेवा — वेगळे बँक खाते उघडा.',
        'प्रत्येक पावतीचा फोटो घ्या आणि Google Drive मध्ये सेव्ह करा.',
      ],
    },
  },
];

export const moduleAccentColors: Record<string, string> = {
  gst: '#FF9933',
  payments: '#22C55E',
  security: '#3B82F6',
  marketing: '#EC4899',
  accounting: '#8B5CF6',
};
