/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Value = IDL.Variant({
  'completed' : IDL.Null,
  'locked' : IDL.Null,
  'unlocked' : IDL.Null,
});
export const Milestone = IDL.Record({
  'id' : IDL.Nat,
  'status' : Value,
  'title' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'illustrationUrl' : IDL.Text,
  'description' : IDL.Text,
});
export const TechnologyJourney = IDL.Record({
  'milestones' : IDL.Vec(Milestone),
});

export const idlService = IDL.Service({
  'getUserJourney' : IDL.Func([], [TechnologyJourney], ['query']),
  'initializeJourney' : IDL.Func([], [], []),
  'markMilestoneCompleted' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Value = IDL.Variant({
    'completed' : IDL.Null,
    'locked' : IDL.Null,
    'unlocked' : IDL.Null,
  });
  const Milestone = IDL.Record({
    'id' : IDL.Nat,
    'status' : Value,
    'title' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'illustrationUrl' : IDL.Text,
    'description' : IDL.Text,
  });
  const TechnologyJourney = IDL.Record({ 'milestones' : IDL.Vec(Milestone) });
  
  return IDL.Service({
    'getUserJourney' : IDL.Func([], [TechnologyJourney], ['query']),
    'initializeJourney' : IDL.Func([], [], []),
    'markMilestoneCompleted' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };